/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.cliente;


import javax.swing.JOptionPane;

/**
 *
 * @author igorm
 */
public class Saque extends javax.swing.JFrame {
    private double valorSaque;
    private String cpfLogado;
    UsuarioLogadoCliente cLogado = new UsuarioLogadoCliente();

/**
 * 
 * @return 
 */
    public double getValorSaque() {
        return valorSaque;
    }
/**
 * 
 * @param valorSaque 
 */
    public void setValorSaque(double valorSaque) {
        this.valorSaque = valorSaque;
    }

    /**
     * Creates new form Saque
     */
    public Saque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_saque10 = new javax.swing.JButton();
        btn_sauque20 = new javax.swing.JButton();
        btn_saque50 = new javax.swing.JButton();
        btn_saque100 = new javax.swing.JButton();
        btn_sacar = new javax.swing.JButton();
        btn_cancelarSaque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_valorSaque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_saque10.setText("R$10,00");
        btn_saque10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saque10ActionPerformed(evt);
            }
        });

        btn_sauque20.setText("R$20,00");
        btn_sauque20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sauque20ActionPerformed(evt);
            }
        });

        btn_saque50.setText("R$50,00");
        btn_saque50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saque50ActionPerformed(evt);
            }
        });

        btn_saque100.setText("R$100,00");
        btn_saque100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saque100ActionPerformed(evt);
            }
        });

        btn_sacar.setText("Sacar");
        btn_sacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sacarActionPerformed(evt);
            }
        });

        btn_cancelarSaque.setText("Cancelar");
        btn_cancelarSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarSaqueActionPerformed(evt);
            }
        });

        jLabel1.setText("Outro valor:");

        txt_valorSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valorSaqueActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SAQUE RÁPIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_valorSaque)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_saque100, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(btn_saque50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sauque20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_saque10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelarSaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sacar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_saque10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sauque20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_saque50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_saque100)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sacar)
                    .addComponent(btn_cancelarSaque))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 */
    private void btn_saque10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saque10ActionPerformed
        valorSaque = 10.00;
        JOptionPane.showMessageDialog(rootPane, valorSaque);
    }//GEN-LAST:event_btn_saque10ActionPerformed
/**
 * 
 * @param evt 
 */
    private void btn_sauque20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sauque20ActionPerformed
        valorSaque = 20.00;
        JOptionPane.showMessageDialog(rootPane, valorSaque);
                    
    }//GEN-LAST:event_btn_sauque20ActionPerformed
/**
 * 
 * @param evt 
 */
    private void btn_saque50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saque50ActionPerformed
        valorSaque = 50.00;
        JOptionPane.showMessageDialog(rootPane, valorSaque);
    }//GEN-LAST:event_btn_saque50ActionPerformed
/**
 * 
 * @param evt 
 */
    private void btn_saque100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saque100ActionPerformed
        valorSaque = 50.00;
        JOptionPane.showMessageDialog(rootPane, valorSaque);
    }//GEN-LAST:event_btn_saque100ActionPerformed
/**
 * 
 * @param evt 
 */
    private void txt_valorSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valorSaqueActionPerformed
        
    }//GEN-LAST:event_txt_valorSaqueActionPerformed
/**
 * 
 * @param evt 
 */
    private void btn_sacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sacarActionPerformed
        valorSaque = Double.parseDouble(txt_valorSaque.getText());

        JOptionPane.showMessageDialog(rootPane, valorSaque);
    }//GEN-LAST:event_btn_sacarActionPerformed
/**
 * 
 * @param evt 
 */
    private void btn_cancelarSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarSaqueActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarSaqueActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarSaque;
    private javax.swing.JButton btn_sacar;
    private javax.swing.JButton btn_saque10;
    private javax.swing.JButton btn_saque100;
    private javax.swing.JButton btn_saque50;
    private javax.swing.JButton btn_sauque20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_valorSaque;
    // End of variables declaration//GEN-END:variables
}
